title: Welcome to Coin Cohort
author: Panoramedia
email: panoramedia@gmail.com
description: > # this means to ignore newlines until "baseurl:"
 
twitter_username: macrod68
github_username:  macrod68

sass:
    style: compressed
